Makefile
Here is the output when I run `make test`:
```
go list ./... | xargs go test -ldflags '-X "github.com/pingcap/dumpling/v4/cli.ReleaseVersion=6342838-dev" -X "github.com/pingcap/dumpling/v4/cli.BuildTimestamp=2019-12-27 03:20:19" -X "github.com/pingcap/dumpling/v4/cli.GitHash=6342838472f82a8dd141930b4b4a843cc71e3855" -X "github.com/pingcap/dumpling/v4/cli.GitBranch=HEAD" -X "github.com/pingcap/dumpling/v4/cli.GoVersion=go version go1.13.4 linux/amd64"' -coverprofile=coverage.txt -covermode=atomic
go: parsing $GOFLAGS: non-flag "'-X"
go: parsing $GOFLAGS: non-flag "'-X"
make: *** [Makefile:21: test] Error 123
```
It seems the error is related to `$GOFLAGS` [environment variable](https://go-review.googlesource.com/c/go/+/126656/).
Renaming `GOFLAGS` can solve this problem.
=> rename GOFLAGS to GOLDFLAGS

cmd/dumpling/main.go, go.mod, go.sum, v4/export/config.go, v4/export/dump.go, v4/export/dump_test.go
Support sorting output by primary key.
Use [DATA-DOG/go-sqlmock](https://github.com/DATA-DOG/go-sqlmock) to mock `database/sql` related types.
=> support sorting output by primary key

v4/export/dump.go, v4/export/sql.go, v4/export/sql_test.go
Changes:
- add `sql.go` and move related functions into it.
- merge/split some functions.
- rename dump_test.go to sql_test.go
=> refactor: move the functions from dump.go to sql.go

v4/export/ir_impl.go, v4/export/ir_impl_test.go
The method `HasNext()` of the interface `RowIter` should have no side effect.
Changes:
- reimplement `rowIter`
=> bugfix: make RowIter.HasNext idempotent

go.mod, go.sum, v4/export/config.go, v4/export/dump.go, v4/export/dump_test.go, v4/export/error.go, v4/export/prepare.go, v4/export/sql.go, v4/export/sql_test.go
Changes:
- refactor `Dump()`: we first list all the tables, then start dumping.
- add tests for `dumpTable()`.
- add three kinds of consistency control: 
- lock all tables
- flush tables with read lock
- snapshot
- add some SQL convenient functions.
=> add support for consistency control

cmd/dumpling/main.go, v4/export/config.go, v4/export/consistency.go, v4/export/consistency_test.go, v4/export/dump.go, v4/export/dump_test.go, v4/export/prepare.go, v4/export/sql.go
Changes:
- Add command line option `consistency` and `snapshot`
- Move consistency-related code to a new file `consistency.go`
- Add unit tests for `consistency.go`
=> consistency: move code to a new file and add unit tests

cmd/dumpling/main.go, tests/file_size/run.sh, v4/export/consistency_test.go, v4/export/ir_impl.go, v4/export/ir_impl_test.go, v4/export/prepare_test.go, v4/export/writer.go, v4/export/writer_util.go
Changes:
- add integration tests: SQL files are split into size close to the given configuration.
- fix the one-offset bug in `tableDataChunks.Rows()`: calling it multiple times should not push forward its inner `*sql.Rows`.
- add test for `sizedRowIter`.
- add test for `prepareDumpingDatabases`.
- rewrite `SimpleWriter`.
=> *: add integration test for dumping in given file size

v4/export/dump.go, v4/export/metadata.go, v4/export/metadata_test.go
Add feature https://github.com/pingcap/dumpling/issues/43.
---
Support output a metadata into output dir after dump operation. DM need the position in metadata to get the start checkpoint for syncer in `all-mode`.
An example of Mydumper's metadata:
```
Started dump at: 2020-03-10 15:53:25
SHOW MASTER STATUS:
Log: ON.000001
Pos: 7502
GTID:6ce40be3-e359-11e9-87e0-36933cb0ca5a:1-29
Finished dump at: 2020-03-10 15:53:25
```
=> Output metadata after the dump operation

cmd/dumpling/main.go, v4/export/config.go, v4/export/dump.go
if noData is specific, dumpling will not dump table data,
if noSchemas is specific, dumpling will not dump table schema.
=> main: add noData\noSchemas cli parameters

go.mod, go.sum, tests/empty_database/run.sh, v4/export/black_white_list.go, v4/export/black_white_list_test.go, v4/export/dump.go, v4/export/prepare.go
1. update tidb-tools to fix match nil pointer problem https://github.com/pingcap/tidb-tools/pull/334.
2. When dumping databases without tables, dumpling won't generate create database sqls. This PR solves this problem.
=> fix dumpling dumping databases without tables

tests/no_table_and_db_name/run.sh, v4/export/writer.go
fix #79 by name the file exported without table and DB name to `result.x.csv`.
=> name export result without table name to `result.x.csv`

cmd/dumpling/main.go, docs/cn/user-guide.md, docs/en/user-guide.md, go.mod, go.sum, tests/_utils/run_dumpling, tests/file_size/run.sh, tests/no_table_and_db_name/run.sh
Fix #85, fix the `-F` part of #76.
* `-F`'s unit is now MiB rather than Bytes. Additionally, allow explicitly setting the unit (e.g. `-F 64MiB`).
* `--statement-size` is now `-s` rather than `-S`.
* `--sql` is now `-S` rather than `-s` (cc @AndrewDi)
* `--host` is now `-h` rather than `-H`
* Added `-T`
=> Adjust CLI parameters to make them the same as mydumper

cmd/dumpling/main.go, v4/export/error.go
Fix #69.
1. avoid adding duplicate stack info
2. save stack info into log. Print simple info to the users. example:
```bash
./bin/dumpling 
Release version: 
Git commit hash: e5fd9c6124696e09626cd662fa7fc897716da4de
Git branch:      refineErrorStack
Build timestamp: 2020-06-02 07:39:27Z
Go version:      go version go1.13.4 darwin/amd64
[2020/06/02 15:39:35.029 +08:00] [ERROR] [main.go:169] ["dump failed error stack info"] [error="dial tcp 127.0.0.1:4000: connect: connection refused"] [errorVerbose="err = dial tcp 127.0.0.1:4000: connect: connection refused\ngoroutine 1 [running]:\nruntime/debug.Stack(0x1610b20, 0xc000138370, 0x16115a0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/pingcap/dumpling/v4/export.withStack(0x1610b20, 0xc000138370, 0xc0000bc070, …
```
=> refine output error stack info

cmd/dumpling/main.go, v4/export/config.go, v4/export/ir.go, v4/export/sql_type.go, v4/export/test_util.go, v4/export/writer.go, v4/export/writer_util.go, v4/export/writer_util_test.go
Resolve https://github.com/pingcap/dumpling/issues/113
Add arguments "csv-separator" and "csv-delimiter" to support specialized csv separator and delimiter.
Tests 
- Unit test
Side effects
=> support specialized csv separator and delimiter

v4/export/dump.go, v4/export/metadata.go, v4/export/metadata_test.go
1. Now we get tables before we flush all tables, it's not safe when there are tables concurrently written.
2. Support record `show slave status` info in metadata for mysql/mariaDB.
3. Fix the problem that can't set snapshot `lock` when server type is `tidb`.
1. For consistency `flush`: lock tables -> record metadata -> get tables list
For consistency `lock`:  record metadata -> get tables list -> lock tables
2. Add metadata support in `metadata.go`.
3. Check whether consistency is `snapshot` before add `snapshot` session variable.
Tests 
- Unit test
Manually check metadata for tidb/mysql. Looks fine to me.
Side effects
- Fix the bug that flush tables may not work for tables to dump
=> fix concurrency problem

tests/null_unique_index/run.sh, v4/export/ir_impl.go
Fix the problem that when picked up field is unique index NULL but dumpling skipped the NULL value.
Add nullValueCondition to check for the first file like mydumper. A related integration is also added.
Tests 
- Unit test
- Fix the bug that dumpling omit the NULL value when `--r` is specified.
=> fix unique key null bug

v4/export/dump.go, v4/export/prepare.go
`resolveAutoConsistency` should run after `conf.ServerInfo` is detected. Or it will be set to `none`.
Move `resolveAutoConsistency` to after `detectServerInfo`.
Tests 
- Unit test
=> fix auto consistency

v4/export/dump.go, v4/export/sql.go, v4/export/sql_test.go
dumpling should support `datetime` type snapshot. But dumpling doesn't parse tso for `datetime` so that it fails set pd gcTS.
Use `SELECT unix_timestamp("%s")` to get unix timestamp to avoid time zone problem.
Tests 
- Unit test
- fix bug dumpling fails to parse tso bug when tidb verison >= v4.0.0
=> parse tso for snapshot

v4/export/connectionsPool.go, v4/export/consistency.go, v4/export/dump.go, v4/export/sql.go, v4/export/writer_util.go
1. When dumpling `Export` is finished, db pool is not closed. Because `defer pool.Close()` only closes the previous connection pool.
2. Get metadata should be earlier than creating connection pool.(For consistency none).
1. Add `defer newPool.Close()` to avoid ambiguity.
2. Put getting metadata before creating connections pool.
3. Make `consistency.TearDone` as defer to avoid lock is not released.
Tests 
- Unit test
=> fix connection close and no-lock metadata

cmd/dumpling/main.go, v4/export/config.go, v4/export/ir_impl.go, v4/export/sql.go, v4/export/sql_test.go
resolve https://github.com/pingcap/dumpling/issues/134
Add argument `--complete-insert` in dumpling.
Tests 
- Unit test
- No code
=> support argument "--complete-insert"

v4/export/config.go, v4/export/dump.go
export GetDSN to reuse code, when using dumpling as a dependency
⬆️
Tests 
- Pass CI
Side effects
=> export GetDSN in dependency usage

v4/export/config.go, v4/export/dump.go, v4/export/metadata.go, v4/export/metadata_test.go
support DM's scenario: when migrate from a DB that can't FTWRL, dumpling uses inconsistent dump. Record the location after connection pool established to indicate DM leave safe mode
metadata now
```
Started dump at: 2020-08-26 17:54:52
SHOW MASTER STATUS:
Log: mysql-bin.000002
Pos: 194
GTID:09bec856-ba95-11ea-850a-58f2b4af5188:1-103
SHOW MASTER STATUS: /* AFTER CONNECTION POOL ESTABLISHED */
Log: mysql-bin.000002
Pos: 199
GTID:09bec856-ba95-11ea-850a-58f2b4af5188:1-103
Finished dump at: 2020-08-26 17:54:52
```
Tests 
- Unit test
Side effects
=> export: record location after connection pool established

v4/export/prepare.go, v4/export/prepare_test.go, v4/export/sql.go
Dumpling's error hint is not clear enough.
1. add SQL to database error message
2. Users can't specify `where` and `sql` option at the same time. dumpling will return an error in `adjust` now. close #154.
Tests 
- Unit test
=> improve dumpling error info

cmd/dumpling/main.go, v4/export/config.go
`--allow-cleartext-password` is required to be able to use Aurora token authentication. It's always combined with TLS so is not actually sent in clear on the wire.
Tests 
- support Aurora token authentication with --allow-cleartext-password
=> Allow clear text password

cmd/dumpling/main.go, v4/export/config.go
If the user doesn't set `statement-size`, the dumped statement in the SQL file might be really huge.
set default `statement-size` to `1000000`
Tests 
- Unit test
=> set default statement size for dumpling

v4/export/sql.go
For MySQL 8.0+ selected fields may not be returned in the original order. (In MySQL 5.7+ and TiDB they do)
```sql
mysql> SELECT COLUMN_NAME,EXTRA,ORDINAL_POSITION FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='test' AND TABLE_NAME='t_1';
+-------------+----------------+------------------+
| COLUMN_NAME | EXTRA          | ORDINAL_POSITION |
+-------------+----------------+------------------+
| b           |                |                2 |
| c           |                |                3 |
| d           |                |                4 |
| id          | auto_increment |                1 |
+-------------+----------------+------------------+
4 rows in set (0.00 sec)
mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.19    |
+-----------+
1 row in set (0.01 …
```
=> order selected field by ORDINAL_POSITION

cmd/dumpling/main.go, v4/export/config.go, v4/export/dump.go, v4/export/sql.go
Dumpling doesn't support customized session variables now.
Add `params` argument to support session params in dumping progress. For example, `--params "character_set_client=latin1,character_set_connection=latin1"`
Tests 
- Unit test
Manually set `--params` and it looks good.
- support --params argument
=> support session parameters

v4/export/consistency.go, v4/export/metadata.go, v4/export/metadata_test.go, v4/export/sql.go, v4/export/writer_util.go
When dumpling dumps data from earlier MySQL who doesn't have GTID (for example, MySQL 5.5.60), dumpling will fail to generate metadata.
```sql
mysql> select version();
+------------+
| version()  |
+------------+
| 5.5.60-log |
+------------+
1 row in set (0.00 sec)
mysql> show master status;
+------------------+----------+--------------+------------------+
| File             | Position | Binlog_Do_DB | Binlog_Ignore_DB |
+------------------+----------+--------------+------------------+
| mysql-bin.000001 |     4879 |              |                  |
+------------------+----------+--------------+------------------+
1 row in set (0.00 sec)
```
```log
[2020/10/22 14:33:07.112 +08:00] [INFO] [config.go:180] ["detect server type"] [type=MySQL]
[2020/10/22 14:33:07.112 +08:00] [INFO] …
```
=> fix metadata for earlier mysql

v4/export/dump.go, v4/export/metadata.go, v4/export/metadata_test.go
1. For TiDB, metadata will use TSO from `show master status`, which is the current TiDB TSO. If the user sets `--snapshot`, it will be different from that.
2. For TiDB not setting `--snapshot`, we will get a snapshot TSO at first to set PD gc-ttl. After that, we will use `show master status` to get another snapshot TSO, which appears to be different from the first one.
Use snapshot TSO fetched at first expect for consistency lock for TiDB.
Tests 
- Unit test
- fix the problem that TiDB  pos in metadata is not accurate
=> fix tidb master status bug

v4/export/ir_impl.go
https://github.com/pingcap/dumpling/issues/186
Tests 
- Unit test
- No code
Side effects
- Breaking backward compatibility
=> skip concurrent dump due to no valid smax or smin

v4/export/config.go
```log
./bin/dumpling -h xx -P yy -u root -T A.B
Release version: v4.0.8-9-g7633719
Git commit hash: 763371960a2ba2ae242d4557e887425f9a3c29cb
Git branch:      master
Build timestamp: 2020-11-09 09:53:49Z
Go version:      go version go1.13.4 darwin/amd64
parse arguments failed: failed to parse filter: cannot pass --tables-list and --filter together
github.com/pingcap/dumpling/v4/export.(*Config).ParseFromFlags
/Users/chauncy/code/goPath/src/github.com/pingcap/dumpling/v4/export/config.go:396
main.main
/Users/chauncy/code/goPath/src/github.com/pingcap/dumpling/cmd/dumpling/main.go:49
runtime.main
/usr/local/go/src/runtime/proc.go:203
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:1357
```
Update the check rule for `--filter` argument.
Tests 
- Unit test
- Manual …
=> hotfix the bug that -T can't work which is introduced from #194

cmd/dumpling/main.go, v4/export/config.go
Currently, dumpling exit relys on `pflag.ErrHelp`. The exit code will be 2 for dumpling.
Add `FlagHelp` to avoid exiting with code 2. This can also help dm avoid quitted when some user mistakenly set `--help` in `ExtraArgs`.
Tests 
- Unit test
```bash
$ ./bin/dumpling --help
Dumpling is a CLI tool that helps you dump MySQL/TiDB data
Usage:
dumpling [flags]
Flags:
--allow-cleartext-passwords         Allow passwords to be sent in cleartext (warning: don't use without TLS)
--ca string                         The path name to the certificate authority file for TLS connection
--case-sensitive                    whether the filter should be case-sensitive
--cert string                       The path name to the client …
```
=> set --help exit code to zero

v4/export/config.go, v4/export/sql_test.go
Compatible with the old version of tidb client that does not have the prefix 'v' on version info.
我用的3.0.6版本的tidb，执行时会出现以下的panic报错，原因是版本检查的正则表达式默认以'v'为前缀，而3.0.6版本没有'v'前缀
Git commit hash: 0175843056a6068dd2f64afca6277d890934b63c
Git branch:      master
Build timestamp: 2020-06-08 02:26:25Z
Go version:      go version go1.13.4 linux/amd64
[2020/11/04 15:28:55.932 +08:00] [DEBUG] [config.go:105] ["parse server info"] ["server info string"=5.7.25-TiDB-3.0.6]
[2020/11/04 15:28:55.932 +08:00] [INFO] [config.go:118] ["detect server type"] [type=TiDB]
panic: runtime error: slice bounds out of range [1:0]
goroutine 1 [running]:
github.com/pingcap/dumpling/v4/export.ParseServerInfo(0xc000136060, 0x11, 0x11, 0x0)
/home/pingcap/goPath/src/github.com/pingcap/dumpling/v4/export/config.go:123 +0x8ba …
=> Compatible with tidb who doesn't have prefix 'v' on version info

v4/export/config.go, v4/export/consistency.go, v4/export/consistency_test.go, v4/export/dump.go, v4/export/dump_test.go, v4/export/metadata.go, v4/export/metadata_test.go, v4/export/retry.go, v4/export/writer_util.go
https://github.com/pingcap/dumpling/issues/178
When we retry on failed chunks, if mysql connection is broken, the retry will fail directly and will take no effect.
1. Add `trx-consistency-only` option. The default value is true. If it is `false`, dumpling won't release locks until the dumping progress is finished.
2. When dumpling retrys on failed chunks, we should rebuild MySQL connection when it was broken.
* For consistency none and consistency snapshot, we can rebuild MySQL connection directly since it doesn't assure consistent snapshot. But for consistency none we should update metadata after conn for DM when we build new MySQL conn.
* For consistency flush and consistency lock, we can rebuild MySQL connection only when dumpling hold locks during the whole dumping progress …
=> rebuild mysql conn when retry failed chunks and support `trx-consistency-only` parameter

v4/export/writer_util.go
When dumpling dumps tables in CSV formats through `--sql` or `-T`, the performance has a big difference.
After analyzing dumpling will waste a lot of time at `fmt.Sprintf`. However, `selected` is fixed for a `tableIR`.
Flame graph:
Replace `tblIR.SelectedField()` with `selectedFields`.
Tests 
- Unit test
Performance comparison(20G tpcc data, one thread):
Before:
real    3m2.199s
user    3m28.472s
sys     0m43.862s
After:
real    2m35.890s
user    2m52.984s
sys     0m42.854s
- fix csv format performance bug
=> writer_util: fix csv format performance bug

v4/export/dump.go
fix the problem that `metaConn` is not closed.
Add `defer metaConn.Close()`.
Tests 
- Unit test
Test using the library and it works fine now.
=> dump/: fix metaConn hold lock

cmd/dumpling/main.go, go.mod, v4/export/block_allow_list.go, v4/export/config.go, v4/export/dump.go, v4/export/http_handler.go, v4/export/metrics.go, v4/export/status.go, v4/export/writer.go, v4/export/writer_util.go
1. close https://github.com/pingcap/dumpling/issues/225. Dumpling won't check unparsed arguments now. It's not easy for users to find spell errors.
2. https://github.com/pingcap/dumpling/issues/223. Some logs in dumpling are not clear enough. For example, we print the estimated count without table name. It's hard to debug.
3. Users can't get current dumpling work status and progress from logs now.
1. Check unparsed arguments and return an error to users.
2. Refine dumpling's log info and adjust some log's level.
3. Add status printer in dumper.
Tests 
- Unit test
1. example for unparsed arguments:
```
$ ./bin/dumpling -P 4000 -T test.order_line -r 20 -F 10B where "id<5"
Release version: v4.0.8-31-gd75dc72
Git commit …
```
=> *: refine dumpling log hint system

tests/_utils/run_services, tests/all_generate_column/conf/diff_config.toml, tests/basic/run.sh, tests/e2e/conf/diff_config.toml, tests/e2e_csv/conf/diff_config.toml, tests/ignore_generate_column/conf/diff_config.toml, tests/rows/conf/diff_config.toml, tests/rows_extreme_int/conf/diff_config.toml, v4/export/config.go, v4/export/dump.go
https://github.com/pingcap/dumpling/issues/232
`dumpling`'s default `tidb-mem-quota-query` is 32GB which may cause TiDB OOM.
Don't set `tidb-mem-quota-query` when it's not specified (Use TiDB's default configuration).
Tests 
- Unit test
Side effects
- Don't set tidb_mem_quota_query when it's not specified.
=> export: delete default tidb mem quota query configuration

tests/basic/run.sh, v4/export/writer.go
When `conf.SQL` is specified and query is failed, dumpling will panic.
Check error before we use ir.
Tests 
- Unit test
- fix the problem that dumpling panic when meeting an error at executing `--sql`
=> fix the problem that dumpling panic when meeting an error at executing `--sql` 

go.mod, v4/export/config.go, v4/export/dump.go, v4/export/writer.go, v4/export/writer_util.go
https://github.com/pingcap/dumpling/issues/236
GCS's `Writer` will use the context when we create the `Writer` to close the external file. If we `teardown` after this context is canceled, it will return a `context canceled` error.
Use an upper context for `ExternalStorage.Create`.
Tests 
- Unit test
Dumpling can write data files successfully on my GCS.
=> gcs: fix dumpling bug

tests/basic/run.sh, tests/no_table_and_db_name/run.sh, v4/cli/versions.go, v4/export/config.go, v4/export/config_test.go, v4/export/consistency_test.go, v4/export/dump.go, v4/export/prepare_test.go, v4/export/sql_test.go, v4/export/writer_test.go
Users may get confused with the SQLs dumped by `--sql` option because it's illegal.
1. Mark `--sql` as hidden since it's incompatible with lightning.
2. Add version info in dumpling.log.
3. Adjust `filetype` automatically.
Tests 
- Unit test
- Mark `--sql` as hidden.
=> *: refine user experience

v4/export/dump.go, v4/export/metrics.go, v4/export/sql.go, v4/export/status.go
add estimate total rows count
add prometheus metrics to save estimate_total_rows before you dump data
it does not work for `-S or --sql` and views data
=> add estimate total rows count to metrics for dump table

v4/export/config.go, v4/export/dump.go, v4/export/dump_test.go, v4/export/sql_type.go
fix https://github.com/pingcap/dumpling/issues/243
Use `writerCtx` to avoid `taskChan` get blocked after the writer quitted. 
Tests 
- Unit test
- fix the problem that dumpling gets stuck after the database connection is lost
=> dump: fix the problem that dumpling gets stuck after the database connection is lost

v4/export/dump.go, v4/export/ir_impl.go, v4/export/sql.go, v4/export/sql_test.go
Although we can make sure TiDB won't OOM through the help of TiDB tablesample. But if we didn't specify `--rows` to open tablesample, TiDB will still OOM.
implement solution 2 in https://github.com/pingcap/dumpling/issues/232
Try to split the whole dump table SQL to several small queries to concatenate their results.
Tests 
- Unit test
- Manual test:
Test dumping 1.2TB data serially (with clustered index enabled), the data rows lines can match.
```log
[2021/03/28 22:31:00.483 +00:00] [INFO] [collector.go:212] ["backup Success summary: total backup ranges: 3, total success: 3, total failed: 0, total take(backup time): 7h12m34.659704485s, total take(real time): 7h12m34.659726417s, total size(MB): 1178105.36, avg speed(MB/s): 45.39, total rows: 2172298300"]
```
```
mysql> …
```
=> dump: add split big tidb query to several small queries

v4/export/sql.go
fix resetDBWithSessionParams if value is int or float
try to parse `params` values string to int or float.
=> Add conn session vars

Makefile, go.mod, go.sum, v4/export/dump.go, v4/export/dump_test.go, v4/export/sql.go, v4/export/sql_test.go, v4/export/writer_util_test.go
https://github.com/pingcap/dumpling/pull/260 introduced some bugs.
Fix them.
Tests 
- Unit test
=> sql: fix table sample sql generator bug

v4/export/metrics.go
estimateTotalRowsCounter didn't respect labelNames, so panicked when using dumpling as a library and changing labelNames
Tests 
- Manual test (WIP)
Side effects
=> export: fix a metric not using labelNames

v4/export/dump.go, v4/export/writer_util_test.go, v4/log/log.go
close https://github.com/pingcap/dumpling/issues/269
Replace `pingcap/log`'s global logger with dumpling's to make sure pd client's log is printed to dumpling's log for dumpling binary.
Tests 
- Unit test
1. Run `./bin/dumpling -P 4000 -h 127.0.0.1 -u root -L dumpling.log --loglevel fatal`:
no log is printed.
2. Run `./bin/dumpling -P 4000 -h 127.0.0.1 -u root -L dumpling.log`:
All logs are printed to `dumpling.log`. 
```log
[2021/04/13 16:31:56.847 +08:00] [INFO] [versions.go:55] ["Welcome to dumpling"] ["Release Version"=v5.0.0-nightly-12-g5228322] ["Git Commit Hash"=52283228cf6ca2c8adfd2147e3f7de074298a8d3] ["Git Branch"=replacePDClientLogger] ["Build timestamp"="2021-04-13 08:12:34"] ["Go Version"="go version …
```
=> log: replace pingcap global logger when start dumpling binary

go.mod, go.sum, tests/basic/run.sh, v4/export/config.go, v4/export/dump.go, v4/export/dump_test.go, v4/export/metrics.go, v4/export/sql.go, v4/export/sql_test.go, v4/export/status.go, v4/export/writer_util_test.go, v4/log/log.go
Some features are not cherry-picked to release-5.0.
Cherry-pick PRs on the master branch to release-5.0.
BugFix:
- Fix the format problem for connection session variables. https://github.com/pingcap/dumpling/pull/265
- Fix panic bugs for metrics when used as library https://github.com/pingcap/dumpling/pull/266, https://github.com/pingcap/dumpling/pull/267
- Fix the problem that pd client's logs are not printed to dumpling's https://github.com/pingcap/dumpling/pull/270 
Feature:
- Add estimate total rows count to metrics for dump table. https://github.com/pingcap/dumpling/pull/254
Tests:
- Add more tests for sample SQL generator https://github.com/pingcap/dumpling/pull/262
Tests 
- Unit test
=> *: cherry-pick recent PRs for dumpling v5.0.1

v4/export/sql.go, v4/export/sql_test.go
this error is hard to reproduce, so I added a 10 minutes sleep before any dump indeed occurs. The error may be sliently different but I think the root cause is same . Here's the log
```
[2021/06/03 19:20:30.262 +08:00] [INFO] [gc_worker.go:1531] ["[gc worker] sent safe point to PD"] [uuid=5e7451a0ff80001] ["safe point"=425385803120640001]
...
[2021/06/03 19:22:21.578 +08:00] [INFO] [set.go:312] ["load snapshot info schema"] [conn=5813] [SnapshotTS=425385803120640000]
...
[2021/06/03 19:22:21.579 +08:00] [INFO] [conn.go:812] ["command dispatched failed"] [conn=5813] [connInfo="id:5813, addr:127.0.0.1:62687 status:10, collation:utf8mb4_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="SET tidb_snapshot='2021-06-03 19:01:00'"] [txn_mode=PESSIMISTIC] …
```
=> export: don't +1 TSO when set GC safepoint

.gitignore, v4/export/sql.go
Issue: https://github.com/pingcap/dumpling/issues/309
- `WITH CONSISTENT SNAPSHOT` is not supported by MemSQL (same for Vitess).
- `SHOW CREATE DATABASE` is not supported by MemSQL.
Tests 
- Support for backing up MySQL compatible databases that don't support `START TRANSACTION  ... WITH CONSISTENT SNAPSHOT`
- Support for backing up MySQL compatible databases that don't support `SHOW CREATE TABLE`
=> export: initial work to support MemSQL/SingleStore

v4/export/block_allow_list.go, v4/export/block_allow_list_test.go, v4/export/dump.go, v4/export/prepare.go, v4/export/prepare_test.go
In https://github.com/pingcap/dumpling/pull/305, we have switched the method to get table info to `SHOW TABLE STATUS`. To reduce the access to databases, we'd better filter databases before we executing `SHOW TABLE STATUS`.
Filter databases before `SHOW TABLE STATUS` through `conf.Filter`.
Tests 
- Unit test
Dump databases and check the log. The databases are filtered before `SHOW TABLE STATUS`.
=> prepare: filter databases before show table status

v4/export/config.go, v4/export/dump.go, v4/export/sql.go, v4/export/sql_test.go
cherry-pick pingcap/tidb#29500 to release-5.2
Tests 
- Unit test
- No code
Side effects
- Breaking backward compatibility
=> make version check more compatible
