pingcap/dumpling

- v4/export/dump_test.go
- v4/export/writer_test.go
* add unit test for dump.go: TestDumpDatabase
* add unit test for writer.go: TestWriteDatabaseMeta, TestWriteTableMeta, TestWriteTableData
> unittest: add unit tests for dump.go and writer.go

- cmd/dumpling/main.go
- v4/export/config.go
- v4/export/dump.go
- v4/export/prepare.go
- v4/log/log.go
Add a function `SetLogger` because DM need to combine logger with dumpling's.
> add SetLogger to support combine log with DM

- v4/export/black_white_list.go
- v4/export/config.go
- v4/export/dump.go
- v4/export/http_handler.go
- v4/export/ir_impl.go
- v4/export/prepare.go
- v4/export/sql.go
- v4/export/writer.go
- v4/export/writer_util.go
- v4/log/log.go
log.go wrap command logger level, rename all log.Zap to call log wrap method
> log: rename all log.Zap to log

- v4/export/consistency.go
- v4/export/consistency_test.go
- v4/export/sql.go
When use tidb without tikv, dumpling should not set snapshot consistency.
> consistency: enhance auto resolve consistency

- cmd/dumpling/main.go
- v4/export/config.go
- v4/export/ir.go
- v4/export/sql_type.go
- v4/export/writer.go
- v4/export/writer_util.go
- v4/export/writer_util_test.go
When export to csv file, user can customize null value in csv file.
> export: add CsvNullValue Cli usage

- cmd/dumpling/main.go
- v4/export/black_white_list.go
- v4/export/config.go
- v4/export/dump.go
- v4/export/sql.go
- v4/export/writer.go
Add cmd parameter, if specific `sql`, dumpling should executer sql and dump result(Only support dump to csv format now)
> dump: add dump data with sql

- README.md
- docs/cn/user-guide.md
- docs/en/user-guide.md
I translated the user guide at `docs/cn` into English.
> add english userguide.

- cmd/dumpling/main.go
- docs/cn/user-guide.md
- docs/en/user-guide.md
- go.mod
- go.sum
- v4/export/black_white_list.go
- v4/export/black_white_list_test.go
- v4/export/config.go
- v4/export/dump.go
- v4/export/dump_test.go
- v4/export/prepare.go
- v4/export/prepare_test.go
Fix #64, fix #65, close #81.
Replaced the black-white-list filter by the new [table-filter](https://github.com/pingcap/tidb-tools/tree/master/pkg/table-filter). Use it like:
```sh
./dumpling -u root -P 14000 -H 172.16.5.189 -f db1.t1 -f db1.t2
```
> Implement --filter and --case-sensitive

- README.md
- cmd/dumpling/main.go
- v4/export/sql.go
fix https://github.com/pingcap/dumpling/issues/92 and fix https://github.com/pingcap/dumpling/issues/91
> fix negative threads bug and rows argument problem

- cmd/dumpling/main.go
- v4/export/black_white_list.go
- v4/export/sql_type.go
- v4/export/sql_type_test.go
- v4/export/writer_util.go
resolve https://github.com/pingcap/dumpling/issues/98
> Resolve csv data mismatch

- v4/export/prepare.go
- v4/export/prepare_test.go
- v4/export/sql.go
Fix #109 
Select all tables/views at one time.
Tests 
- Unit test
Side effects
- Fix the problem that dumpling get blocked when tidb cluster has a lot of tables.
> reduce select usage when query tables

- cmd/dumpling/main.go
- v4/export/config.go
- v4/export/prepare.go
- v4/export/writer.go
- v4/export/writer_test.go
reopened PR for https://github.com/pingcap/dumpling/pull/120
implement https://github.com/pingcap/dumpling/issues/114
Add `--output-filename-format` argument to support specifying the format of output filename.
Tests 
- Unit test
- support specify output filename format
> support specify ouput filename format

- v4/export/connectionsPool.go
- v4/export/dump.go
If we don't close connection after export, the function that uses dumplings as library may get blocked.
Add release function
Tests 
- Unit test
> close connection after export

- go.mod
- go.sum
update filter dependency to solve https://github.com/pingcap/tidb-tools/pull/382
update go mod
Tests 
- No code
> tidb-tools: update dependency

- v4/export/config.go
close #139 
- add json string method, omit the password
Tests 
manually check with DM
> omit password in string method

- README.md
> add sig prompt

- .github/challenge-bot.yml
https://github.com/tikv/pd/pull/2981
Add challenge bot config
Set default sig info.
> github: add challenge bot config to set default sig

- .github/ISSUE_TEMPLATE/challenge-program.md
- .github/pull_request_template.md
- install.sh
Add challenge program template.
Add challenge program template.
Tests 
- No code
Side effects
None
None
> github: add challenge program template

- go.sum
- v4/export/sql.go
- v4/export/sql_test.go
https://github.com/pingcap/dumpling/issues/187
Tests 
- Unit test
- No code
Side effects
- Breaking backward compatibility
> refine order by primary key

- tests/chaos/run.sh
- v4/export/sql.go
- v4/export/writer_util.go
1. `Dumpling` may return error when picking primary integer index because we don't check database name at https://github.com/pingcap/dumpling/blob/master/v4/export/sql.go#L642.
2. `Dumpling` is in lack of chaos test.
1. refine pick mechism
2. add mysql chaos test
Tests 
- Unit test
> add MySQL chaos test

- cmd/dumpling/main.go
- v4/export/config.go
- v4/export/consistency.go
- v4/export/consistency_test.go
- v4/export/dump.go
- v4/export/prepare.go
- v4/export/prepare_test.go
- v4/export/writer.go
- v4/export/writer_test.go
Refactor dumpling code to improve readability & maintainability.
- Define the struct `Dumper` to wrap common arguments used by most functions.
- Extract the initialization steps into a few functions.
- Remove unreasonable fields in `Config` like `externalStorage`.
Tests 
- Unit test
Side effects
N/A
N/A
> refactor dump.go

- v4/export/metadata.go
- v4/export/metadata_test.go
part of https://github.com/pingcap/dm/issues/1320
don't write SHOW MASTER STATUS when lacking privilege
Tests 
- Unit test
- Manual test
Side effects
- Breaking backward compatibility (**but keep same with mydumper**)
> export: don't write SHOW MASTER STATUS when lacking privilege

- v4/export/writer.go
afte retry, the newly created connection may lost and didn't close
asign it back to `w.conn`, so could close it
Tests 
Side effects
> export: catch new connection to close it in future

- tests/views/run.sh
- v4/export/dump.go
close #226 
don't dump data for view
Tests 
Side effects
> dump: don't dump data for view

- v4/export/config.go
`--transactional-consistency` is not frequently used and most users don't know its meaning.
mark `--transactional-consistency` as hidden.
Tests 
- Unit test
This command is not found in --help
> config: mark --transactional-consistency as hidden

- v4/export/test_util.go
None
None
Tests 
- No code
None
None
> export: ignore unused parameters

- .github/workflows/go.yml
- Makefile
- v4/export/dump.go
- v4/export/ir.go
- v4/export/ir_impl.go
- v4/export/test_util.go
- v4/export/writer.go
- v4/export/writer_util.go
- v4/export/writer_util_test.go
1. Dumpling's log is not clear when some bugs occurred.
2. We didn't check `FileRowIter.Error` when there is no next. However, we check this when we start this `rowIter`. But this is safer.
1. Add more log.
2. Check Error.
Tests 
- Unit test
> *: add logs and try fixing error log

- v4/export/dump.go
- v4/export/sql.go
- v4/export/sql_test.go
- v4/export/sql_type.go
close https://github.com/pingcap/dumpling/issues/259
support new where sql generator.
Tests 
- Unit test
Side effects
> dump: support new where sql generator

- v4/export/dump.go
- v4/export/ir_impl.go
- v4/export/sql.go
- v4/export/sql_test.go
close https://github.com/pingcap/dumpling/issues/263
This is a manual cherry-pick of #257
/assign lichunzhu
> [release-5.0] dump: add split big tidb query to several small queries

- v4/export/status.go
a supplement of https://github.com/pingcap/dumpling/pull/266
Use `AddCounter` to avoid nil pointer.
Tests 
- Unit test
> export: fix estimateTotalRowsCounter nil pointer

- v4/export/config.go
Make it clear that dumpling also accepts a MySQL timestamp format as string for the snapshot.
Tests 
- No code
> config: Correct usage info for snapshot flag

- v4/export/config.go
as title
as title
Tests 
- No code
Side effects
> config: do not show ssl bytes

- v4/export/dump.go
- v4/export/http_handler.go
- v4/export/sql.go
- v4/export/writer_util.go
- v4/log/log.go
1. Dumpling's warning log with error stack may terrify users. Users may think the dump task is failed but actually, it's not.
2. Dumpling may fail when dumpling account lacks privileges for `MYSQL.TiDB`.
1. Change error stack to short error.
2. Ignore all errors when trying auto adjust gc to PD.
Tests 
- Unit test
> *: update dumpling log and pd usage

- tests/all_generate_column/conf/diff_config.toml
- tests/e2e/conf/diff_config.toml
- tests/e2e_csv/conf/diff_config.toml
- tests/ignore_generate_column/conf/diff_config.toml
- tests/rows/conf/diff_config.toml
- tests/rows_extreme_int/conf/diff_config.toml
sync_diff_spector's config has been updated.
update configs to v2.
> tests: fix sync_diff configs for CI

- tests/_utils/check_sync_diff
- tests/all_generate_column/conf/diff_config.toml
- tests/e2e/conf/diff_config.toml
- tests/e2e_csv/conf/diff_config.toml
- tests/ignore_generate_column/conf/diff_config.toml
- tests/rows/conf/diff_config.toml
- tests/rows_extreme_int/conf/diff_config.toml
The new sync-diff-inspector is not compatibility with the `check_diff` shell.
remove the output directory before run sync-diff-inspector.
> tests: fix check diff

- tests/_utils/check_sync_diff
- tests/all_generate_column/conf/diff_config.toml
- tests/e2e/conf/diff_config.toml
- tests/e2e_csv/conf/diff_config.toml
- tests/ignore_generate_column/conf/diff_config.toml
- tests/rows/conf/diff_config.toml
- tests/rows_extreme_int/conf/diff_config.toml
#380  and #386 are lock each other, need to merge them into one pr.
revert and merge.
> tests: revert #380 and #386
